import React,{useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {getTrials,getTrialOperations} from '../api/client';
import {Activity,AlertTriangle,CalendarDays,CheckCircle2,ClipboardCheck,FileClock,FlaskConical,HeartPulse,Pill,ShieldCheck,TrendingUp,Users} from 'lucide-react';
import Avatar from './Avatar';

const badge=s=>s==='ACTIVE'||s==='COMPLETED'||s==='RESOLVED'?'bg-emerald-100 text-emerald-700':s==='WITHDRAWN'?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-700';
const Metric=({icon:Icon,label,value,note,color='text-blue-600 bg-blue-50'})=><div className="glass-card p-5"><div className={`mb-4 grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon className="h-5 w-5"/></div><p className="text-3xl font-black text-slate-950">{value??'—'}</p><p className="mt-1 text-sm font-bold text-slate-700">{label}</p><p className="mt-1 text-xs text-slate-400">{note}</p></div>;

export default function TrialOperations(){const{data:trials}=useQuery({queryKey:['trials'],queryFn:getTrials});const[id,setId]=useState(null);useEffect(()=>{if(!id&&trials?.length)setId(trials[0].id)},[trials,id]);const{data,isLoading}=useQuery({queryKey:['trial-operations',id],queryFn:()=>getTrialOperations(id),enabled:!!id});const completed=(data?.visits||[]).filter(v=>v.status==='COMPLETED');const efficacy=completed.filter(v=>v.efficacyScore!=null);return <div className="space-y-7 pb-12">
 <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-blue-900 p-7 text-white shadow-2xl"><div className="absolute right-0 top-0 h-48 w-48 rounded-full bg-cyan-400/20 blur-3xl"/><div className="relative flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black tracking-[.2em] text-cyan-300">LONGITUDINAL STUDY CONTROL</p><h1 className="mt-2 text-3xl font-black">From enrollment to study completion</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100">Monitor treatment exposure, safety, efficacy, visits, protocol compliance, amendments, and participant outcomes throughout the study.</p></div><select value={id||''} onChange={e=>setId(Number(e.target.value))} className="rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-bold text-white outline-none">{trials?.map(t=><option className="text-slate-900" key={t.id} value={t.id}>{t.code} — {t.title}</option>)}</select></div></section>
 {isLoading?<div className="glass-card p-12 text-center text-slate-500">Loading study operations…</div>:data&&<>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Users} label="Participants" value={data.participants.length} note={`${data.statusCounts.ACTIVE||0} currently active`}/><Metric icon={CalendarDays} label="Study day" value={data.studyDay} note="Longitudinal follow-up" color="bg-indigo-50 text-indigo-600"/><Metric icon={ClipboardCheck} label="Visit completion" value={`${data.visitCompletionRate}%`} note={`${completed.length} visits completed`} color="bg-emerald-50 text-emerald-600"/><Metric icon={AlertTriangle} label="Safety events" value={data.adverseEvents.length} note={`${data.seriousAdverseEvents} serious`} color="bg-rose-50 text-rose-600"/><Metric icon={FileClock} label="Open deviations" value={data.openDeviations} note="Protocol compliance" color="bg-amber-50 text-amber-600"/></div>
 <div className="grid gap-6 xl:grid-cols-3"><section className="glass-card overflow-hidden xl:col-span-2"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-black text-slate-900">Participant journey</h2><p className="text-sm text-slate-500">Enrollment, treatment, monitoring, and outcomes</p></div><HeartPulse className="text-blue-600"/></div><div className="divide-y">{data.participants.map(p=><div key={p.id} className="flex flex-wrap items-center gap-4 p-4"><Avatar name={p.patientName} size="sm"/><div className="min-w-[170px] flex-1"><p className="font-bold text-slate-900">{p.patientName}</p><p className="text-xs text-slate-500">{p.canonicalId} · {p.treatmentArm}</p></div><div><p className="text-xs text-slate-400">Adherence</p><p className="font-black text-slate-800">{p.adherencePercent!=null?`${p.adherencePercent}%`:'Pending'}</p></div><div><p className="text-xs text-slate-400">Next milestone</p><p className="text-sm font-bold text-slate-700">{p.nextVisitDate||'Closed'}</p></div><span className={`rounded-full px-3 py-1 text-[11px] font-black ${badge(p.status)}`}>{p.status}</span></div>)}</div></section>
 <section className="glass-card p-5"><div className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-cyan-600"/><h2 className="font-black">Efficacy signal</h2></div><p className="mt-1 text-xs text-slate-500">Recorded outcome scores over completed visits</p><div className="mt-6 flex h-44 items-end gap-3 border-b border-l border-slate-200 px-4">{efficacy.map((v,i)=><div key={v.id} className="group flex flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] font-bold text-slate-500">{v.efficacyScore}</span><div style={{height:`${Math.max(15,Number(v.efficacyScore))}%`}} className="w-full max-w-10 rounded-t-lg bg-gradient-to-t from-blue-600 to-cyan-300 transition group-hover:brightness-110"/><span className="w-14 truncate text-center text-[9px] text-slate-400">V{i+1}</span></div>)}</div></section></div>
 <div className="grid gap-6 xl:grid-cols-2"><section className="glass-card overflow-hidden"><div className="border-b p-5"><h2 className="flex items-center gap-2 font-black"><CalendarDays className="h-5 w-5 text-blue-600"/>Visit & dosing schedule</h2></div><div className="max-h-[420px] divide-y overflow-auto">{data.visits.map(v=><div key={v.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-slate-900">{v.visitName}</p><p className="text-xs text-slate-500">{v.patientName} · {v.scheduledDate}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-black ${badge(v.status)}`}>{v.status}</span></div><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-md bg-slate-100 px-2 py-1"><Pill className="mr-1 inline h-3 w-3"/>{v.doseAdministered||'Dose pending'}</span><span className="rounded-md bg-blue-50 px-2 py-1 text-blue-700"><FlaskConical className="mr-1 inline h-3 w-3"/>{v.labName}: {v.labValue??'pending'} {v.labUnit}</span>{v.protocolDeviation&&<span className="rounded-md bg-amber-100 px-2 py-1 font-bold text-amber-800">Deviation: {v.protocolDeviation}</span>}</div></div>)}</div></section>
 <section className="space-y-6"><div className="glass-card overflow-hidden"><div className="border-b p-5"><h2 className="flex items-center gap-2 font-black"><Activity className="h-5 w-5 text-rose-600"/>Safety surveillance</h2></div><div className="divide-y">{data.adverseEvents.map(a=><div key={a.id} className="p-4"><div className="flex justify-between"><p className="font-bold text-slate-900">{a.description}</p><span className={`rounded-full px-2 py-1 text-[10px] font-black ${badge(a.status)}`}>{a.status}</span></div><p className="mt-1 text-xs text-slate-500">{a.patientName} · {a.onsetDate} · {a.severity} · {a.relatedness}</p><p className="mt-2 text-xs font-medium text-slate-700">Action: {a.actionTaken}</p></div>)}</div></div><div className="glass-card overflow-hidden"><div className="border-b p-5"><h2 className="flex items-center gap-2 font-black"><ShieldCheck className="h-5 w-5 text-indigo-600"/>Protocol versions & oversight</h2></div><div className="divide-y">{data.amendments.map(a=><div key={a.id} className="p-4"><div className="flex items-center justify-between"><p className="font-bold text-slate-900">v{a.version} · {a.title}</p><span className="text-xs font-bold text-emerald-700">{a.approvalStatus}</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{a.summary}</p><p className="mt-2 text-[11px] font-bold text-indigo-700">{a.requiresReconsent?'Participant re-consent required':'No re-consent required'} · {a.approvedBy}</p></div>)}</div></div></section></div>
 </>}</div>}
