package com.clinicaltrial.assistant.service;
import com.clinicaltrial.assistant.model.*; import com.clinicaltrial.assistant.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.time.LocalDate; import java.time.temporal.ChronoUnit; import java.util.*;
@Service @RequiredArgsConstructor
public class TrialOperationsService {
 private final TrialRepository trialRepo; private final TrialParticipantRepository participantRepo; private final StudyVisitRepository visitRepo; private final AdverseEventRepository adverseRepo; private final ProtocolAmendmentRepository amendmentRepo; private final AuditService audit;
 @Transactional(readOnly=true) public Map<String,Object> dashboard(Long trialId){
  Trial trial=trialRepo.findById(trialId).orElseThrow(()->new RuntimeException("Trial not found")); var ps=participantRepo.findByTrialIdOrderByEnrolledDateDesc(trialId); var vs=visitRepo.findByParticipantTrialIdOrderByScheduledDateAsc(trialId); var aes=adverseRepo.findByParticipantTrialIdOrderByOnsetDateDesc(trialId); var amendments=amendmentRepo.findByTrialIdOrderByEffectiveDateDesc(trialId);
  Map<String,Object> out=new LinkedHashMap<>(); out.put("trial",Map.of("id",trial.getId(),"code",trial.getTrialCode(),"title",trial.getTitle())); out.put("studyDay",ps.stream().map(TrialParticipant::getEnrolledDate).filter(Objects::nonNull).min(LocalDate::compareTo).map(d->ChronoUnit.DAYS.between(d,LocalDate.now())).orElse(0L));
  out.put("participants",ps.stream().map(this::participant).toList()); out.put("visits",vs.stream().map(this::visit).toList()); out.put("adverseEvents",aes.stream().map(this::adverse).toList()); out.put("amendments",amendments.stream().map(this::amendment).toList());
  Map<String,Long> counts=new LinkedHashMap<>(); for(String s:List.of("SCREENING","ACTIVE","MONITORING","COMPLETED","WITHDRAWN")) counts.put(s,ps.stream().filter(p->s.equals(p.getStatus())).count()); out.put("statusCounts",counts); out.put("seriousAdverseEvents",aes.stream().filter(AdverseEvent::isSerious).count()); out.put("openDeviations",vs.stream().filter(v->v.getProtocolDeviation()!=null&&!v.getProtocolDeviation().isBlank()).count()); out.put("visitCompletionRate",vs.isEmpty()?0:Math.round(100.0*vs.stream().filter(v->"COMPLETED".equals(v.getStatus())).count()/vs.size())); return out;
 }
 @Transactional public Map<String,Object> updateParticipant(Long id,Map<String,String> body){var p=participantRepo.findById(id).orElseThrow(); if(body.containsKey("status"))p.setStatus(body.get("status")); if(body.containsKey("nextVisitDate"))p.setNextVisitDate(LocalDate.parse(body.get("nextVisitDate"))); if(body.containsKey("dsmbStatus"))p.setDsmbStatus(body.get("dsmbStatus")); if(body.containsKey("withdrawalReason"))p.setWithdrawalReason(body.get("withdrawalReason")); participantRepo.save(p);audit.log("PARTICIPANT_STATUS_UPDATED","TrialParticipant",id.toString(),p.getStatus());return participant(p);}
 @Transactional public Map<String,Object> completeVisit(Long id,Map<String,String> body){var v=visitRepo.findById(id).orElseThrow();v.setStatus("COMPLETED");v.setCompletedDate(LocalDate.now());if(body.containsKey("doseAdministered"))v.setDoseAdministered(body.get("doseAdministered"));if(body.containsKey("adherencePercent"))v.setAdherencePercent(new BigDecimal(body.get("adherencePercent")));if(body.containsKey("labValue"))v.setLabValue(new BigDecimal(body.get("labValue")));if(body.containsKey("notes"))v.setNotes(body.get("notes"));visitRepo.save(v);audit.log("STUDY_VISIT_COMPLETED","StudyVisit",id.toString(),v.getVisitName());return visit(v);}
 @Transactional public Map<String,Object> addAdverseEvent(Long participantId,Map<String,String> b){var p=participantRepo.findById(participantId).orElseThrow();var a=AdverseEvent.builder().participant(p).onsetDate(LocalDate.parse(b.getOrDefault("onsetDate",LocalDate.now().toString()))).severity(b.getOrDefault("severity","MILD")).relatedness(b.getOrDefault("relatedness","POSSIBLE")).status("OPEN").serious(Boolean.parseBoolean(b.getOrDefault("serious","false"))).description(b.getOrDefault("description","Clinical event under assessment")).actionTaken(b.getOrDefault("actionTaken","Investigator review initiated")).build();adverseRepo.save(a);audit.log("ADVERSE_EVENT_RECORDED","AdverseEvent",a.getId().toString(),a.getSeverity());return adverse(a);}
 private Map<String,Object> participant(TrialParticipant p){Map<String,Object>m=new LinkedHashMap<>();m.put("id",p.getId());m.put("patientId",p.getPatient().getId());m.put("patientName",p.getPatient().getFirstName()+" "+p.getPatient().getLastName());m.put("canonicalId",p.getPatient().getCanonicalPatientId());m.put("status",p.getStatus());m.put("enrolledDate",p.getEnrolledDate());m.put("treatmentArm",p.getTreatmentArm());m.put("consentVersion",p.getConsentVersion());m.put("baselineComplete",p.isBaselineComplete());m.put("adherencePercent",p.getAdherencePercent());m.put("nextVisitDate",p.getNextVisitDate());m.put("dsmbStatus",p.getDsmbStatus());m.put("withdrawalReason",p.getWithdrawalReason());return m;}
 private Map<String,Object> visit(StudyVisit v){Map<String,Object>m=new LinkedHashMap<>();m.put("id",v.getId());m.put("participantId",v.getParticipant().getId());m.put("patientName",v.getParticipant().getPatient().getFirstName()+" "+v.getParticipant().getPatient().getLastName());m.put("visitName",v.getVisitName());m.put("scheduledDate",v.getScheduledDate());m.put("completedDate",v.getCompletedDate());m.put("status",v.getStatus());m.put("doseAdministered",v.getDoseAdministered());m.put("adherencePercent",v.getAdherencePercent());m.put("labName",v.getLabName());m.put("labValue",v.getLabValue());m.put("labUnit",v.getLabUnit());m.put("efficacyScore",v.getEfficacyScore());m.put("notes",v.getNotes());m.put("protocolDeviation",v.getProtocolDeviation());return m;}
 private Map<String,Object> adverse(AdverseEvent a){Map<String,Object>m=new LinkedHashMap<>();m.put("id",a.getId());m.put("patientName",a.getParticipant().getPatient().getFirstName()+" "+a.getParticipant().getPatient().getLastName());m.put("onsetDate",a.getOnsetDate());m.put("severity",a.getSeverity());m.put("relatedness",a.getRelatedness());m.put("status",a.getStatus());m.put("serious",a.isSerious());m.put("description",a.getDescription());m.put("actionTaken",a.getActionTaken());return m;}
 private Map<String,Object> amendment(ProtocolAmendment a){Map<String,Object>m=new LinkedHashMap<>();m.put("id",a.getId());m.put("version",a.getVersion());m.put("title",a.getTitle());m.put("summary",a.getSummary());m.put("effectiveDate",a.getEffectiveDate());m.put("approvalStatus",a.getApprovalStatus());m.put("requiresReconsent",a.isRequiresReconsent());m.put("approvedBy",a.getApprovedBy());return m;}
}
